# Raspberry Pi brcmfmac + eero mesh: disable firmware roaming to stop the
# reassociation churn that produces 802.11 status_code=16 (auth timeout) and
# leaves the Pi with no IP at boot. See WiFi reliability notes.
options brcmfmac roamoff=1
