#!/bin/bash
# select-default-audio.sh — choose the ALSA default output at boot, and point
# EmulationStation's volume control at the right mixer for it.
#
# Prefer the USB sound card (named "WaveshareUSB" by 90-waveshare-usb-audio.rules
# regardless of port). If it isn't present — not installed, or it failed to
# enumerate — fall back to the connected HDMI display's speakers. Net effect: the
# build always has working audio AND a working volume slider, dongle or not.
#
# Volume control notes (hard-won — see project build notes):
#   * EmulationStation's volume slider drives an ALSA simple control named by its
#     "AudioDevice" setting. The WaveShare USB card's *real* control is "Speaker"
#     (its "Master" is inert), so we point ES at Speaker.
#   * HDMI has NO hardware volume control at all, so for the HDMI fallback we wrap
#     it in an ALSA softvol that exposes a software "Master" and point ES there.
#   * This only works if there is no sound server (PipeWire/PulseAudio) grabbing
#     the card — picadeinstall masks PipeWire for exactly this reason.
#
# Run once at boot by select-default-audio.service, BEFORE EmulationStation.
set -u

ASOUND=/etc/asound.conf
ES_CFG=/home/pi/.emulationstation/es_settings.cfg
USB_NAME="WaveshareUSB"
log(){ logger -t select-default-audio "$*"; echo "$*"; }

# Set one EmulationStation setting (update in place, or append; flat-file format).
set_es(){  # $1=name $2=value
    local name="$1" val="$2"
    mkdir -p "$(dirname "$ES_CFG")"
    [ -f "$ES_CFG" ] || printf '<?xml version="1.0"?>\n' > "$ES_CFG"
    if grep -q "name=\"$name\"" "$ES_CFG"; then
        sed -i "s|\(<string name=\"$name\" value=\)\"[^\"]*\"|\1\"$val\"|" "$ES_CFG"
    else
        echo "<string name=\"$name\" value=\"$val\" />" >> "$ES_CFG"
    fi
    chown pi:pi "$ES_CFG" 2>/dev/null || true
}

# --- USB sound card present? -> make it the default (dmix so apps can share) ---
if aplay -l 2>/dev/null | grep -qi "$USB_NAME"; then
    cat > "$ASOUND" <<EOF
# Auto-generated by select-default-audio.service: USB sound card present.
pcm.!default {
    type plug
    slave.pcm "dmix_waveshare"
}
pcm.dmix_waveshare {
    type dmix
    ipc_key 2048
    ipc_key_add_uid yes
    slave { pcm "hw:$USB_NAME,0"; rate 48000; channels 2 }
}
ctl.!default { type hw; card $USB_NAME }
EOF
    # Point ES at the USB card's real control ("Speaker"); make sure it's audible.
    amixer -c "$USB_NAME" sset Master 100% >/dev/null 2>&1 || true   # inert, leave open
    set_es AudioCard default
    set_es AudioDevice Speaker
    log "USB sound card ($USB_NAME) present -> default audio = USB, ES volume = Speaker"
    exit 0
fi

# --- No USB card -> connected HDMI, wrapped in softvol (HDMI has no volume) ---
# Best-effort map: drm HDMI-A-1 -> vc4hdmi0, HDMI-A-2 -> vc4hdmi1.
HDMI_CARD="vc4hdmi0"
for s in /sys/class/drm/card*-HDMI-A-*/status; do
    [ "$(cat "$s" 2>/dev/null)" = "connected" ] || continue
    case "$s" in
        *HDMI-A-1*) HDMI_CARD="vc4hdmi0" ;;
        *HDMI-A-2*) HDMI_CARD="vc4hdmi1" ;;
    esac
    break
done

cat > "$ASOUND" <<EOF
# Auto-generated by select-default-audio.service: no USB card; HDMI + softvol.
# softvol over plughw (NOT dmix — dmix fails to initialize on the vc4 HDMI
# device's format constraints; plughw handles the conversion).
pcm.!default {
    type plug
    slave.pcm "softvol_hdmi"
}
pcm.softvol_hdmi {
    type softvol
    slave.pcm "plughw:$HDMI_CARD,0"
    control { name "Master"; card "$HDMI_CARD" }
    min_dB -51.0
    max_dB 0.0
    resolution 256
}
ctl.!default { type hw; card $HDMI_CARD }
EOF
# Prime the softvol "Master" control so it exists before ES attaches (1s silence).
aplay -d 1 -f S16_LE -r 48000 -c 2 -D default /dev/zero >/dev/null 2>&1 || true
set_es AudioCard default
set_es AudioDevice Master
log "No USB sound card -> default audio = HDMI ($HDMI_CARD) + softvol, ES volume = Master"
